// <auto-generated />
namespace DemoApplication.Data.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    public sealed partial class MembershipAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MembershipAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201211202232558_Membership Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
