// <auto-generated />
namespace DemoApplication.Infrastructure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UsersRolesandUserClaimsAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersRolesandUserClaimsAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201303260331061_Users Roles and UserClaims Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
