// <auto-generated />
namespace DemoApplication.Infrastructure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Origin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Origin));
        
        string IMigrationMetadata.Id
        {
            get { return "201304011248250_Origin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
