// <auto-generated />
namespace DemoApplication.Infrastructure.Data.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    public sealed partial class Userchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Userchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201211221854230_User changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
